### ISSUE TITLE
Apache upgrade request

### ISSUE THREAD

**Issue by godspeed20** [cburgmer/greenyet#21]
I might be wrong, but we're getting warnings in the logs of green yet relating to Apache responseprocesscookies , and it says the cookie has an invalid expires attribute. It looks like this might be due to the http client... Same can be seen here:
https://github.com/gradle/gradle/issues/1596
https://issues.apache.org/jira/browse/HTTPCLIENT-1077

I can't tell which version is in use from the project file though (looks like it doesn't even use Apache somehow) but you please help take a quick look?

Thanks

**Comment by cburgmer** [comment]
Hey, sorry for the late answer.

greenyet indeeds ships with http-kit, not the Apache HttpClient. Please double check that you are not running a fork, similar to PR #19.

I've bumped all dependencies in the latest 2 commits. You might want to check whether that fixes anything. You can build the jar yourself by running
```
./lein ring uberjar
```

**Comment by godspeed20** [comment]
Thanks Chris, hope you're well. I didn't notice that pr, let me double check, maybe that's the culprit after all

**Comment by godspeed20** [comment]
Looks like we're using a fork so I'll dig that way, sorry about that. Hope you're well
